//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printing3dApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectRecord
    {
        public int id { get; set; }
        public string ProjectTitle { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<double> BuildHeight { get; set; }
        public string Comments { get; set; }
        public string Material { get; set; }
        public string Process { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual StatusState StatusState { get; set; }
    }
}
